[package]
name = "hyperbeam"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "hyperbeam"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.20"
rustler_codegen = "0.20"
lazy_static = "1.2"
hyper = "0.12.24"
futures = "0.1"
